Crop = {'Barley': {'BH-902': ['Uttar Pradesh',
                       'Rajasthan',
                       'Haryana',
                       'Punjab',
                       'Uttarakhand',
                       'Delhi'],
            'DWRB 73': ['Uttar Pradesh',
                        'Rajasthan',
                        'Haryana',
                        'Punjab',
                        'Delhi'],
            'Pusa Losar  (BH- 380)': ['Himachal Pradesh', 'Uttarakhand']},
 'Bengal Gram': {'MNK-1': ['Karnataka',
                           'Andhra Pradesh',
                           'Tamil Nadu',
                           'Orissa'],
                 'PKV KABULI-4': ['Maharashtra', 'Madhya Pradesh']},
 'Chickpea ': {'Ujjawal (IPCK2004-29)': ['Maharashtra',
                                         'Gujarat',
                                         'Rajasthan']},
 'Cluster Bean': {'HG 2-20': ['Uttar Pradesh',
                              'Gujarat',
                              'Rajasthan',
                              'Haryana'],
                  'HG 884': ['Uttar Pradesh',
                             'Gujarat',
                             'Rajasthan',
                             'Haryana',
                             'Madhya Pradesh']},
 'Cotton': {'CICR-3 (CISA 614)': ['Uttar Pradesh', 'Haryana', 'Punjab'],
            'CNH012': ['Maharashtra', 'Gujarat', 'Madhya Pradesh'],
            'VBCH 2231': ['Maharashtra',
                          'Gujarat',
                          'Madhya Pradesh',
                          'Orissa']},
 'Cowpea (Fodder)': {'UPC 628': ['Maharashtra',
                                 'Gujarat',
                                 'Rajasthan',
                                 'Assam',
                                 'Bihar',
                                 'Haryana',
                                 'Jharkhand',
                                 'Orissa',
                                 'Punjab',
                                 'Uttarakhand',
                                 'West Bengal']},
 'Desi Cotton': {'FDK 124': ['Rajasthan', 'Haryana', 'Punjab']},
 'Fieldpea': {'Aman  (IPF 5-19)': ['Uttar Pradesh',
                                   'Rajasthan',
                                   'Haryana',
                                   'Punjab',
                                   'Uttarakhand',
                                   'Delhi'],
              'Dantiwada Fieldpea 1 (SKNP 04-09)': ['Uttar Pradesh',
                                                    'Bihar',
                                                    'Jharkhand',
                                                    'West Bengal'],
              'GOMATI (TRCP-8)': ['Uttarakhand']},
 'Finger Millet': {'GPU 67': ['Karnataka',
                              'Tamil Nadu',
                              'Maharashtra',
                              'Jharkhand',
                              'Uttarakhand']},
 'French Bean': {'Gujarat Rajmash-1 (DPR 88-1-2)': ['Maharashtra',
                                                    'Gujarat',
                                                    'Rajasthan',
                                                    'Madhya Pradesh']},
 'Groundnut': {'GPBD 5': ['Jharkhand', 'Manipur'],
               'Girnar - 3 (PBS 12160)': ['Manipur', 'Orissa', 'West Bengal'],
               'Kadiri Harithandhra (K 1319)': ['Karnataka', 'Maharashtra']},
 'Horse Gram': {'CRIDALATHA (CRHG-4)': []},
 'Indian Mustard': {'CORAL 432 (PAC 432)(Hybrid)': ['Uttar Pradesh',
                                                    'Rajasthan',
                                                    'Madhya Pradesh',
                                                    'Uttarakhand'],
                    'DRMR 601 (NRCDR 601)': ['Rajasthan',
                                             'Haryana',
                                             'Punjab',
                                             'Delhi'],
                    'Pusa Mustard 26 (NPJ-113)': ['Uttar Pradesh',
                                                  'Rajasthan',
                                                  'Haryana',
                                                  'Punjab',
                                                  'Delhi'],
                    'Pusa Mustard 27 (EJ-17)': ['Uttar Pradesh',
                                                'Rajasthan',
                                                'Madhya Pradesh',
                                                'Uttarakhand']},
 'Jute': {'ARPITA  (JBC-5)': ['Assam', 'West Bengal'],
          'SUDHANGSU (JBO-1)': ['Assam', 'Bihar', 'Orissa', 'West Bengal']},
 'Lentil': {'Pant Lentil-7(Pant L-024)': ['Uttar Pradesh', 'Haryana', 'Punjab'],
            'Pant Lentil-8(Pant L-063)': ['Uttar Pradesh',
                                          'Rajasthan',
                                          'Haryana',
                                          'Punjab',
                                          'Uttarakhand',
                                          'Delhi']},
 'Linseed': {'JLS-67 (Shival)': ['Uttar Pradesh',
                                 'Rajasthan',
                                 'Madhya Pradesh'],
             'JLS-73 (SLS-73)': ['Maharashtra',
                                 'Uttar Pradesh',
                                 'Gujarat',
                                 'Rajasthan',
                                 'Madhya Pradesh'],
             'Ruchi (LCK 5021)': ['Uttar Pradesh',
                                  'Assam',
                                  'Bihar',
                                  'Jharkhand',
                                  'West Bengal']},
 'Maize': {'DHM 119 (BH 4062)': ['Karnataka',
                                 'Andhra Pradesh',
                                 'Tamil Nadu',
                                 'Maharashtra'],
           'HQPM-4': ['Karnataka',
                      'Andhra Pradesh',
                      'Maharashtra',
                      'Gujarat',
                      'Rajasthan',
                      'Bihar',
                      'Haryana',
                      'Jharkhand',
                      'Madhya Pradesh',
                      'Orissa',
                      'Punjab',
                      'Delhi'],
           'HSC1': ['Himachal Pradesh', 'Uttarakhand'],
           'MCH 36 (Hybrid) (DKC 9099)': ['Karnataka',
                                          'Tamil Nadu',
                                          'Maharashtra'],
           'PMH 4 (JH 31153)': ['Uttar Pradesh', 'Haryana', 'Punjab', 'Delhi'],
           'PMH 5 (JH 3110)': ['Gujarat', 'Rajasthan', 'Madhya Pradesh']},
 'Mesta': {'SHRESTHA (JRM-5)': ['Andhra Pradesh',
                                'Maharashtra',
                                'Assam',
                                'Bihar',
                                'Orissa',
                                'West Bengal'],
           'SNEHA  (JRM-3)': []},
 'Mungbean': {'PKV AKM-4 (AKM-9904)': ['Karnataka', 'Tamil Nadu', 'Orissa']},
 'Napier Bajra Hybrid': {'Phule Jaywant (RBN-13)': ['Karnataka',
                                                    'Andhra Pradesh',
                                                    'Kerala',
                                                    'Tamil Nadu',
                                                    'Maharashtra',
                                                    'Gujarat',
                                                    'Madhya Pradesh']},
 'Oat': {'JO 03-91 (SC)': ['Maharashtra',
                           'Uttar Pradesh',
                           'Gujarat',
                           'Madhya Pradesh'],
         'Narendra Jayee -1 (NDO - 1)': [],
         'OS 346': ['Maharashtra', 'Gujarat', 'Madhya Pradesh']},
 'Paddy': {'(CNI 383-5-11)': [],
           'CR Dhan 401 (REETA) ': ['Andhra Pradesh',
                                    'Tamil Nadu',
                                    'Orissa',
                                    'West Bengal'],
           'CR Dhan 501 (IET 19189)': ['Uttar Pradesh', 'Assam'],
           'CR Dhan 601 (IET 18558)': ['Assam', 'Orissa', 'West Bengal'],
           'Chinsurah Rice (IET 19140)': ['Andhra Pradesh',
                                          'Tamil Nadu',
                                          'Gujarat',
                                          'Orissa',
                                          'West Bengal'],
           'IGKVR-1 (IET 19569)': ['Madhya Pradesh', 'Orissa'],
           'IGKVR-2 (IET 19795)': ['Bihar', 'Orissa'],
           'RC Maniphou 11 (IET 20193)': ['Manipur', 'Meghalaya']},
 'Pearl Millet': {'86M64 (MSH 203) (Hybrid)': ['Tamil Nadu',
                                               'Maharashtra',
                                               'Gujarat',
                                               'Rajasthan'],
                  'HHB 226  (MH 1479)': ['Uttar Pradesh',
                                         'Gujarat',
                                         'Rajasthan',
                                         'Haryana',
                                         'Madhya Pradesh',
                                         'Punjab'],
                  'MH 1540 (86M64) (Hybrid)': ['Karnataka',
                                               'Andhra Pradesh',
                                               'Tamil Nadu',
                                               'Maharashtra'],
                  'MH 1541 (86M53) (Hybrid)': ['Karnataka',
                                               'Andhra Pradesh',
                                               'Tamil Nadu',
                                               'Maharashtra'],
                  'Nandi-61 (MH-1548)': ['Gujarat',
                                         'Rajasthan',
                                         'Haryana',
                                         'Punjab',
                                         'Delhi'],
                  'Nandi-65 (MH-1549)': ['Gujarat',
                                         'Rajasthan',
                                         'Haryana',
                                         'Punjab',
                                         'Delhi'],
                  'RHB 177 (MH 1486)': ['Gujarat', 'Rajasthan', 'Haryana']},
 'Sesame': {'Rajasthan Till 351 (RT 351)': ['Karnataka',
                                            'Maharashtra',
                                            'Uttar Pradesh',
                                            'Gujarat',
                                            'Rajasthan',
                                            'Himachal Pradesh',
                                            'Jammu and Kashmir',
                                            'Haryana',
                                            'Punjab']},
 'Sugarcane': {'Co-0218': ['Karnataka',
                           'Andhra Pradesh',
                           'Kerala',
                           'Tamil Nadu',
                           'Maharashtra'],
               'Karan 5 (Co 0124)': ['Uttar Pradesh',
                                     'Rajasthan',
                                     'Haryana',
                                     'Punjab',
                                     'Uttarakhand'],
               'Karan 6 (Co 0239)': ['Uttar Pradesh',
                                     'Rajasthan',
                                     'Haryana',
                                     'Punjab',
                                     'Uttarakhand']},
 'Tall Fescue Grass': {'EC 178182': ['Himachal Pradesh', 'Uttarakhand']},
 'Urdbean': {'Mash 391 (LU 391)': ['Karnataka',
                                   'Andhra Pradesh',
                                   'Tamil Nadu',
                                   'Orissa'],
             'Mash 479 (KUG 479)': ['Uttar Pradesh',
                                    'Haryana',
                                    'Punjab',
                                    'Uttarakhand']},
 'Wheat': {'DBW39': ['Uttar Pradesh',
                     'Assam',
                     'Bihar',
                     'Jharkhand',
                     'Orissa',
                     'West Bengal'],
           'MACS 6222': ['Karnataka',
                         'Andhra Pradesh',
                         'Tamil Nadu',
                         'Maharashtra'],
           'MPO(JW)  1215 (MPO 1215)': ['Gujarat',
                                        'Rajasthan',
                                        'Madhya Pradesh'],
           'Netravati  (NIAW 1415)': ['Karnataka'],
           'PDW 314': ['Uttar Pradesh',
                       'Rajasthan',
                       'Himachal Pradesh',
                       'Haryana',
                       'Punjab',
                       'Uttarakhand',
                       'Delhi'],
           'Pusa Prachi (HI 1563)': ['Uttar Pradesh',
                                     'Assam',
                                     'Bihar',
                                     'Jharkhand',
                                     'Orissa',
                                     'West Bengal'],
           'Pusa Suketi  HS 507': ['Himachal Pradesh',
                                   'Jammu and Kashmir',
                                   'Uttarakhand'],
           'VL Gehun 907 (VL 907)': ['Himachal Pradesh',
                                     'Sikkim',
                                     'Uttarakhand'],
           'WHD 943': ['Uttar Pradesh',
                       'Rajasthan',
                       'Himachal Pradesh',
                       'Jammu and Kashmir',
                       'Haryana',
                       'Punjab',
                       'Uttarakhand',
                       'Delhi']},
 'Yellow Sarson': {'Pitambari (RYSK-05-02)': ['Gujarat',
                                              'Bihar',
                                              'Haryana',
                                              'Manipur',
                                              'Uttarakhand',
                                              'West Bengal']}}